# for the outputted config.sample
iroha_block_store_path: "/tmp/block-store/"
iroha_torii_port: 50051
iroha_internal_port: 10001
iroha_pg_opt: "host=localhost port=5432 user=postgres password=mysecretpassword" #TODO: practice production-grade secrets-keeping
iroha_max_proposal_size: 3000 # TODO: test the following attributes on 1-2 vCPU 3.75-7.x GB RAM 
iroha_proposal_delay: 10000
iroha_vote_delay: 1000
iroha_mst_enable: 'true'
iroha_mst_expiration_time: 360 # make as small as possible

# for the outputted k8s-iroha.yaml
pod_basename: iroha
service_name: iroha
iroha_replicas: 12
iroha_image: hyperledger/iroha:1.0.0_rc3
postgres_image: postgres:9.5   # TODO: ask devs about total compatibilty with newer versions
postgres_volume_size: 1Gi
blockstore_volume_size: 1Gi