---
  - name: Make CSV header
    shell: >
      echo 'host;port;priv_key_hex;pub_key_hex' > peers.csv
    args:
      chdir: "{{ role_path }}/files"

  - name: Make keys
    command: >
      python {{ role_path }}/files/ed25519.py
    loop: "{{ range(iroha_replicas|int)|list }}"
    register: result

  - name: Generate peers and add to CSV
    shell: >
      echo '{{ pod_basename }}-{{ item }}.{{ service_name }};{{ iroha_internal_port }};{{ result.results[item].stdout_lines[0] }};{{ result.results[item].stdout_lines[1] }}'
      >> {{ role_path }}/files/peers.csv
    args:
      chdir: "{{ role_path }}/files"
    loop: "{{ range(iroha_replicas|int)|list }}"

  - name: Generate config.docker
    template:
      src: config.docker.j2
      dest: "{{ role_path }}/files/conf/config.docker"
    delegate_to: localhost

  - name: Make genesis block file
    command: >
      python3 genesis-add-peers.py add_iroha_peers peers.csv genesis.block 
    args:
      chdir: "{{ role_path }}/files"

  - name: Move genesis block
    command: "cp genesis.block conf/genesis.block"
    args:
      chdir: "{{ role_path }}/files"

  - name: Get peer keys for secrets
    shell: >
      cat peers.csv | grep -E "[A-Fa-f0-9]{64}[;][A-Fa-f0-9]{64}" -o
    register: peer_keys
    args:
      chdir: "{{ role_path }}/files"

  - name: Generate k8s secrets
    template:
      src: k8s-peer-keys.yaml.j2
      dest: "{{ role_path }}/files/k8s-peer-keys.yaml"
    delegate_to: localhost

  - name: Generate k8s config
    template:
      src: k8s-iroha.yaml.j2
      dest: "{{ role_path }}/files/k8s-iroha.yaml"
    delegate_to: localhost